NITTC-ComputerClub/SeiDoc

src/App.tsx, src/admin/components/header.tsx, src/admin/components/rankingList.tsx, src/admin/pages/top.tsx, src/admin/pages/totalRanking.tsx
/admin/totalRanking
issue #178 
DPR
=> 職員用トータルランキング画面の作成

src/admin/components/header.tsx
=> データ出力のパスを変更

src/admin/components/rankingList.tsx, src/admin/components/searchWords.tsx
/admin/top
/admin/totalRanking
においてWarningが出てたのでkeyを追加しました
=> keyがなくて怒られてた

src/admin/components/header.tsx, src/admin/pages/categoryRanking.tsx, src/admin/pages/csvDownload.tsx, src/admin/pages/detail.tsx, src/admin/pages/input.tsx, src/admin/pages/search.tsx, src/admin/pages/top.tsx, src/admin/pages/totalRanking.tsx
issue #235 
setStateとuseSelectorって並列じゃないとダメなんですね
=> fix: login判定をheaderからpagesに移動

src/user/components/header.tsx
=> headerの文言変えた

src/reducers/loginReducer.ts
=> adminにログインできるようになった

src/admin/components/searchWords.tsx
=> /adminの最新検索ワードそれぞれに適切な余白を付与した

src/admin/components/signInForm.tsx, src/user/components/Login/signIn.tsx, src/user/components/searchBar.tsx
Enterを押したら検索する検索バーの実装
admin, userともにsearchBar コンポーネントを使っていたため一箇所のみの変更でOKだった
=> Enterを押したら検索する

src/admin/components/categoryRankingList.tsx, src/admin/components/rankingList.tsx, src/admin/pages/categoryRanking.tsx, src/admin/pages/totalRanking.tsx
=> admin/totalRanking (/categoryRanking)のCSSを当てた

src/user/components/Top/latestSystemList.tsx, src/user/pages/top.tsx
+ systemsにある新しい5つ
地域で絞ったほうが良い？
=> 新しい制度をみれるようにした

src/user/components/Login/drawProfile.ts, src/user/components/Login/fixProfile.tsx, src/user/components/Login/myself.tsx, src/user/components/Login/picture.tsx, src/user/components/Login/selectImage.tsx, src/user/pages/picturePage.tsx
=> /picture 関連のバグの修正

src/App.tsx, src/admin/pages/notFound.tsx
=> add not found

functions/src/index.ts, src/user/components/Top/recommend.tsx
close #135 
cloudfunctionに上がってるのでもううごいてます
=> firebaseから消したらalgoliaSearchからも消す

src/admin/pages/input.tsx, src/admin/pages/top.tsx
=> add: 新制度登録時にアラート&topにリダイレクト

src/actions/action.ts, src/admin/components/adminSystemList.tsx, src/user/components/systemList.tsx
/search?region=豊田市 など
+ tag + region
+ inputValue + region
+ regionのみ
の検索に対応
=> regionを用いた検索

src/admin/pages/input.tsx, src/reducers/detailReducer.ts, src/types/type.ts, src/user/components/Top/recommend.tsx, src/user/pages/registration.tsx, src/user/pages/viewAll.tsx
/admin/newSystem
複数選択可能なcheckboxへ
DPR
=> fix: checkboxに変更

package-lock.json, src/admin/pages/top.tsx
=> add: 青色をSeiDocsカラーに変更

src/admin/pages/newSystem.tsx
/admin/newSystem
post時に条件分岐させて実装
どこが間違ってるとかは出ません
=> fix: 新制度登録でvalidationつける

src/admin/pages/top.tsx
close #227 
/admin でtagの情報をinitするようにしました
=> top画面でtagをinit

src/user/components/Login/drawProfile.ts
=> add: 顔認識後の先の細さを一定にした

src/user/components/Login/fixProfile.tsx
close #288 
/picuteで写真読み込んでデータを修正するときに何もタップしないで修正ボタンを押すとエラー吐いて落ちてたのを修正
=> canvasを押さずに修正ボタンを押すとエラー吐くバグ取り

src/admin/pages/csvDownload.tsx, src/admin/pages/newSystem.tsx
=> fix: フォームのはみ出しを修正

src/user/components/Top/popularSystemList.tsx
前日以前のpopularSystemを表示したほうがいいんじゃない？と思った
1. 前日のdataを取得
2. 3つ以下だった場合1日前のdataを取得
3. 3つ以下だった場合2日前のdataを取得
....
=> popularSystem が取得できなかった場合の処理

src/user/components/Login/signIn.tsx, src/user/components/Login/signUp.tsx
=> login,signIn時に入力不備があればボタンの色を変える
